os: linux
dist: bionic
language: java
jdk: openjdk8

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - chmod +x gradlew
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create use mybuilder

script: ./gradlew build

deploy:
  provider: script
  script: "./gradlew bintrayUpload :docker:publish"
  skip_cleanup: true
  on:
    branch: master
    tags: true
