os: linux
dist: bionic
language: java
jdk: openjdk8

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - chmod +x gradlew

before_script:
  - docker run --rm --privileged docker/binfmt
  - docker buildx create --use --name multiArchBuilder

script: ./gradlew build

deploy:
  provider: script
  script: "./gradlew bintrayUpload :docker:publish"
  skip_cleanup: true
  on:
    branch: master
    tags: true
