version: "3.7"

networks:
  mongo-net:
  postgres-net:

services:

  jupyter-kotlin:
    image: lamba92/kotlin-jupyter:1.0.1
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ~/notebooks
        target: /notebooks
    networks:
      - mongo-net
      - postgres-net
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  postgres:
    image: postgres
    deploy:
      restart_policy:
        delay: 0s
        max_attempts: 10
        window: 5s
      placement:
        constraints:
          - node.role==manager
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  sql-analitycs-server:
    image: lamba92/maadb-project-sql-analytics-server
    networks:
      - postgres-net
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
      mode: global
    environment:
      - DATABASE_URL=jdbc:postgres//postgres:5432/
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
        - 8080:80

  nosql-analitycs-server:
    image: lamba92/maadb-project-nosql-analytics-server
    networks:
      - mongo-net
    depends_on:
      - mongo-supervisor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
      mode: global
    environment:
      - MONGO_URL=mongodb://mongo-supervisor:27017
      - MONGO_DB_NAME=maadb
    ports:
      - 8082:80

  mongo-supervisor:
    image: lamba92/maadb-project-mongo-supervisor
    networks:
      - mongo-net
    depends_on:
      - mongo-cfg-1
      - mongo-cfg-2
      - ms1
      - ms2
      - ms3
      - ms4
      - ms5
      - ms6
      - ms7
      - ms8
      - ms9
      - ms10
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    environment:
      - CONFIGS=mongo-cfg-1:27019,mongo-cfg-2:27019
      - SHARDS=ms1:27018,ms2:27018,ms3:27018,ms4:27018,ms5:27018,ms6:27018,ms7:27018,ms8:27018,ms9:27018,ms10:27018
      - CONFIGS_RPL_NAME=cfgrs
      - SHARDS_RPL_NAME=datars
    ports:
      - 27017:27017

  mongo-cfg-1:
    image: mongo
    command: mongod --configsvr --bind_ip_all --replSet cfgrs
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27019", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s
      placement:
        constraints:
          - node.labels.mongo.role==data1

  mongo-cfg-2:
    image: mongo
    command: mongod --configsvr --bind_ip_all --replSet cfgrs
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27019", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s
      placement:
        constraints:
          - node.labels.mongo.role==data2

  ms1:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms2:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms3:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms4:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms5:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms6:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms7:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms8:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms9:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  ms10:
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet datars
    networks:
      - mongo-net
    healthcheck:
      test: ["CMD", "mongo", "--port", "27018", "--eval", "db.stats()"]
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s

  mongo-express:
    image: mongo-express
    networks:
      - mongo-net
    depends_on:
      - mongo-supervisor
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 10s
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo-supervisor

  sql-data-feeder:
    image: lamba92/maadb-project-sql-data-feeder
    networks:
      - postgres-net
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: none
      mode: replicated
      replicas: 1
    environment:
      - DB_URL=jdbc:postgres//postgres:5432/
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  nosql-data-feeder:
    image: lamba92/maadb-project-sql-data-feeder
    networks:
      - mongo-net
    depends_on:
      - mongo-supervisor
    deploy:
      restart_policy:
        condition: none
      mode: replicated
      replicas: 1
    environment:
      - MONGO_URL=mongodb://mongo-supervisor:27017
      - MONGO_DB_NAME=maadb
