version: "3.7"

volumes:
  postgres-volume:
  jupyter-data:
  mongo-volume:

services:
  jupyter-kotlin:
    image: jupyter-kotlin
    restart: always
    container_name: jupyter-kotlin
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ~/notebooks
        target: /notebooks
      - type: volume
        source: jupyter-data
        target: /root/.jupyter

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data

  sql-analitycs-server:
    image: sql-analytics-server
    container_name: sql-analytics-server
    command: sql-analytics-server
    restart: always
    deploy:
      replicas: 2
    environment:
      - DATABASE_URL="jdbc:postgres//postgres:5432"
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - 8080:80

  mongo-router:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-shard-1:
    image: mongo
    restart: always

  mongo-shard-2:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
