version: "3.7"

volumes:
  postgres-volume:
  jupyter-data:

services:
  jupyter-kotlin:
    build: jupyter-kotlin
    restart: always
    container_name: jupyter-kotlin
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ~/notebooks
        target: /notebooks
      - type: volume
        source: jupyter-data
        target: /root/.jupyter

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data

  sql-analitycs-server:
    build: sql-analytics-server
    container_name: sql-analytics-server
    command: sql-analytics-server
    restart: always
    environment:
      - DATABASE_URL="jdbc:postgres//postgres:5432"
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - 8080:80
